{% set name = "pdm" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdm-{{ version }}.tar.gz
  sha256: 68be6c9ee7f0afb1a324f65926f618521cbe899d3d557011d579d4ce2bfb47fd

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - pdm-pep517 >=0.3.0
    - setuptools
    - wheel
  run:
    - cachecontrol >=0.12.11
    - certifi
    - requests-toolbelt
    - rich >=12.3.0
    - unearth >=0.6.0
    - virtualenv >=20
    - blinker
    - findpython >=0.2.2
    - importlib-metadata >=3.6  # [py<310]
    - python-installer <0.6,>=0.5.1
    - packaging >=20.9
    - pdm-pep517 <2.0.0,>=1.0.0
    - platformdirs
    - python-dotenv >=0.15
    - pyproject-hooks
    - resolvelib >=0.9,<0.10
    - shellingham >=1.3.2
    - tomli >=1.1.0  # [py<311]
    - tomlkit <1,>=0.11.1
    - typing-extensions  # [py<38]

test:
  imports:
    - pdm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pdm/
  summary: Python Development Master
  description: |
    A modern Python package and dependency manager 
    supporting the latest PEP standards.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://pdm.fming.dev/latest/
  doc_url: https://github.com/pdm-project/pdm/tree/main/docs/docs

extra:
  recipe-maintainers:
    - xhochy
    - theAeon
    - daylinmorgan
