{% set name = "pdm" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdm-{{ version }}.tar.gz
  sha256: a861d47d57bc6ef9e99edb09abd620955a37b2835019b6a8918beea3b089a3b7

build:
  entry_points:
    - pdm = pdm.core:main
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - pdm-pep517 >=0.3.0
    - setuptools
    - wheel
  run:
    - cachecontrol >=0.12.11
    - certifi >=2022.6.15
    - requests-toolbelt
    - rich >=12.3.0
    - unearth >=0.6.0
    - virtualenv >=20
    - blinker
    - findpython >=0.2.0
    - importlib-metadata >=3.6  # [py<310]
    - python-installer <0.6,>=0.5.1
    - packaging >=20.9
    - pdm-pep517 >=1.0
    - pep517 >=0.11.0
    - platformdirs
    - python
    - python-dotenv >=0.15
    - resolvelib <0.9,>=0.8
    - shellingham >=1.3.2
    - tomli >=1.1.0  # [py<311]
    - tomlkit <1,>=0.8.0
    - typing-extensions  # [py<38]

test:
  imports:
    - pdm
  commands:
    - pip check
    - pdm --python
  requires:
    - pip

about:
  home: https://pdm.fming.dev/
  summary: Python Development Master
  description: |
    A modern Python package and dependency manager 
    supporting the latest PEP standards.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://github.com/pdm-project/pdm
  doc_url: https://pdm.fming.dev/

extra:
  recipe-maintainers:
    - xhochy
    - theAeon
    - daylinmorgan
